AllCops:
  Exclude:
    - tmp/**/*
    - bin/**/*
    - db/schema.rb
    - agile-direction-ui/**/*
    - spec/**/*.rb
    - vendor/bundle/**/*
    - fantasy-celebrity-front-end/**/*

Metrics/LineLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  MinSize: 10

Style/CommentAnnotation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/AccessorMethodName:
  Description: 'Checks for the naming of a method with get_ or set_'
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments
  Max: 25

Style/SignalException:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/ParenthesesAroundCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 20
